In [5]:
import psycopg2
from sshtunnel import SSHTunnelForwarder

In [62]:
import csv

def listToString(l):
    s = ""
    for i in l:
        s += (i + ",")
    s = s[:-1]
    return s

def castData(curs):
    data = []
    for row in curs:
        data.append(row)
    print("Data casted")
    return data

def toCSV(filename,columns,content):
    with open(filename, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(columns)
        writer.writerows(content)
    print("CSV output file ready")

In [74]:
try:
    with SSHTunnelForwarder(
        ('161.35.123.231', 22),
        ssh_username="postgres",
        ssh_password="dbConn2021!", 
        remote_bind_address=('localhost', 5432)) as server:
        
        print("server connected")

        keepalive_kwargs = {
            "keepalives": 1,
            "keepalives_idle": 60,
            "keepalives_interval": 10,
            "keepalives_count": 5
        }

        params = {
            'database': 'tweetproject',
            'user': 'postgres',
            'password': 'padova2021',
            'host': server.local_bind_host,
            'port': server.local_bind_port,
            **keepalive_kwargs
            }

        conn = psycopg2.connect(**params)
        curs = conn.cursor()
        print("database connected")

        
        #curs.execute("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tweet'")
        """
        columns_name = ['id','label']
        curs.execute("SELECT twitter_id,full_text FROM tweet WHERE in_reply_twitter_id IS NULL") 
        content = castData(curs)
        toCSV('politicians_tweets.csv',columns_name,content)

        curs.execute("SELECT twitter_id,full_text FROM tweet WHERE in_reply_twitter_id IS NOT NULL") 
        content = castData(curs)
        toCSV('reply_tweets.csv',columns_name,content)
        """
        columns_name = ['source','target']
        curs.execute("SELECT twitter_id,in_reply_twitter_id FROM tweet WHERE in_reply_twitter_id IS NOT NULL") 
        content = castData(curs)
        toCSV('edges.csv',columns_name,content)
        
except (Exception) as error:
    print("Connection Failed")
    print(error)

server connected
database connected
Data casted
CSV output file ready

In [72]:
import pandas as pd

data = pd.read_csv('politicians_tweets.csv')
data

                       id                                              label
0     1471972072645709824  Un compañero en toda la línea, del Polo, del C...
1     1471971145129857029  ¿Qué impuestos nuevos hay que crear en Colombi...
2     1471259239800786950  En junio presentamos un plan de empleo juvenil...
3     1470385522782588928  Entiendo el susto de padres y madres frente a ...
4     1470208058961891331  El primer paso para luchar contra la corrupció...
...                   ...                                                ...
1353  1480591118014291969  2/2 Instamos a las autoridades a tomar medidas...
1354  1480349254631804928  Si bien celebramos medidas de aerolíneas orien...
1355  1480330664486780929  Con la #RegionalOcaña participamos en Consejo ...
1356  1481657293271801858  #Análisis Colombia enfrenta la crisis generada...
1357  1480962713572499458  En 2021 la Unidad De Seguridad Y Aseguramiento...

[1358 rows x 2 columns]

In [73]:
data = pd.read_csv('reply_tweets.csv')
data

                        id                                              label
0      1470633537984471044  @sergio_fajardo @RevistaSemana Pa' la celda ,ome!
1      1470628243338416130   @sergio_fajardo @RevistaSemana Att, HidroItuango
2      1470478758989729800                      @OIZuluaga @DespiertaAnt Pfff
3      1472008937679560706  @petrogustavo En Paz Descansa.\n\n(Mejor esa f...
4      1472004668532342785              @petrogustavo https://t.co/XpwDP6GKhR
...                    ...                                                ...
89608  1481256570692460550  El verbo ABUDINEAR muere cuando esa doblehiuep...
89609  1481252468499615745  Por qué no la @? Cobarde. @karenabudi https://...
89610  1481251288901951497   Tras de ladrona, bufona. https://t.co/plT32c7xCY
89611  1480976519514177539                          … https://t.co/sdpQzG3Wqk
89612  1480894195850268672  #ComunidadIEMP #NotiProcu ¡Te puede interesar!...

[89613 rows x 2 columns]